const API=(window.PORTAL_CONFIG?.apiBase||"").replace(/\/$/,"");
const questions=[
 {q:"Una persona eleva la voz porque no puede ingresar. ¿Cuál es la mejor primera respuesta?",o:["Responder con el mismo tono","Escuchar y reconocer su molestia","Amenazar con retirarla"],a:1},
 {q:"¿Qué significa reconocer la emoción?",o:["Aceptar cualquier conducta","Ceder ante su petición","Mostrar que comprendemos cómo se siente"],a:2},
 {q:"¿Cuándo debe detenerse el diálogo?",o:["Cuando hacen una pregunta","Cuando existen amenazas o riesgo de agresión","Cuando el procedimiento tarda"],a:1},
 {q:"¿Qué combina la técnica práctica?",o:["Escucha + límite + opción","Orden + amenaza + sanción","Silencio + retirada"],a:0},
 {q:"¿Cuál frase ayuda a desescalar?",o:["Aquí mando yo","No me importa","Lo que sí puedo hacer es…"],a:2}
];
const form=document.querySelector("#examForm"),submit=document.querySelector("#submitButton"),bar=document.querySelector("#progressBar");
form.innerHTML=questions.map((p,i)=>`<section class="question"><h3>${i+1}. ${p.q}</h3>${p.o.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"><span>${o}</span></label>`).join("")}</section>`).join("");
function answers(){return questions.map((_,i)=>{const x=form.querySelector(`input[name=q${i}]:checked`);return x?Number(x.value):null})}
form.addEventListener("change",()=>{const done=answers().filter(x=>x!==null).length;bar.style.width=`${done/questions.length*100}%`});
form.addEventListener("submit",async e=>{e.preventDefault();const selected=answers();if(selected.some(x=>x===null)){alert("Responde todas las preguntas antes de finalizar.");return}submit.disabled=true;submit.textContent="Guardando...";const hits=selected.filter((x,i)=>x===questions[i].a).length,grade=Math.round(hits/questions.length*100);const incorrect=questions.flatMap((p,i)=>selected[i]===p.a?[]:[{numero:i+1,pregunta:p.q,respuesta_usuario:p.o[selected[i]],respuesta_correcta:p.o[p.a]}]);try{const r=await fetch(`${API}/api/portal/resultados`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({curso_slug:"resolucion-de-conflictos",modalidad:"PRESENCIAL",calificacion:grade,calificacion_maxima:100,total_preguntas:questions.length,respuestas_incorrectas:incorrect})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.mensaje||"No fue posible guardar la evaluación.");form.style.display="none";document.querySelector(".exam-actions").style.display="none";const result=document.querySelector("#result");result.style.display="block";result.classList.add(grade>=70?"approved":"failed");document.querySelector("#score").textContent=`${grade}%`;document.querySelector("#resultTitle").textContent=grade>=70?"Evaluación acreditada":"Evaluación no acreditada";document.querySelector("#resultText").textContent=`Obtuviste ${hits} de ${questions.length} respuestas correctas. Tu resultado quedó registrado como capacitación presencial.`}catch(e){alert(e.message);submit.disabled=false;submit.textContent="Finalizar evaluación"}});
(async()=>{try{const r=await fetch(`${API}/api/portal/session`,{credentials:"include",cache:"no-store"});const d=await r.json();if(!r.ok||!d.autenticado)location.href="index.html"}catch{location.href="index.html"}})();
