const API=(window.PORTAL_CONFIG?.apiBase||"").replace(/\/$/,"");
const loginView=document.querySelector("#loginView"),dashboard=document.querySelector("#dashboardView"),form=document.querySelector("#loginForm"),message=document.querySelector("#loginMessage"),button=document.querySelector("#loginButton");
const diamanteCourse=document.querySelector("#diamanteCourse");
function normalizeService(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ").toUpperCase()}
function isDiamanteService(value){return ["WALMART DIAMANTE","DIAMANTE"].includes(normalizeService(value))}
function showParticipant(p){const netVetExam=document.querySelector("#netVetExam");if(netVetExam)netVetExam.hidden=!["WALMART NET","WALMART VET","NET","VET","WALMART NET Y VET","WALMART VET Y NET"].includes(normalizeService(p.servicio));document.querySelector("#welcomeName").textContent=`Bienvenido, ${p.nombre.split(" ")[0]}`;document.querySelector("#employeeNumber").textContent=`Empleado: ${p.numero_empleado}`;document.querySelector("#serviceName").textContent=`Servicio: ${p.servicio||"Sin asignar"}`;if(diamanteCourse)diamanteCourse.hidden=!isDiamanteService(p.servicio);loginView.style.display="none";dashboard.style.display="block"}
async function session(){const r=await fetch(`${API}/api/portal/session`,{credentials:"include",cache:"no-store"});if(!r.ok)return;const d=await r.json();if(d.autenticado&&d.participante)showParticipant(d.participante)}
form.addEventListener("submit",async e=>{e.preventDefault();message.textContent="";button.disabled=true;button.textContent="Verificando...";try{const r=await fetch(`${API}/api/portal/login`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({nombre:form.nombre.value.trim(),numero_empleado:form.numero_empleado.value.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.mensaje||"No fue posible ingresar.");showParticipant(d.participante)}catch(e){message.textContent=e.message}finally{button.disabled=false;button.textContent="Ingresar"}});
document.querySelector("#logoutButton").addEventListener("click",async()=>{await fetch(`${API}/api/portal/logout`,{method:"POST",credentials:"include"}).catch(()=>{});location.reload()});session().catch(()=>{});
